[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "Benchtop"
version = "0.1.0"
description = "A tool for running simulation experiments formated as PEtab Problems."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Jonah Huggins", email = "JonahRileyHuggins@gmail.com" },
	{ name = "Marc Birtwistle", email = "marc.birtwistle@gmail.com" },
]

license = {text = "GPL-2.0"}

dependencies = [
    "numpy==2.2.4",
	"pandas==2.3.1",
	"pyyaml==6.0.2",
	"tellurium==2.2.11.2"
]

[project.optional-dependencies]
amici = [
	"amici==0.32.0"
]
dev = [
	"pytest>=8.0",
]

[project.scripts]
benchtop = "benchtop.launcher:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
pythonpath = ["src"]
filterwarnings = [
	"ignore::DeprecationWarning",
]
